name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode.app

    - name: Build
      run: |
        xcodebuild clean build \
          -scheme "VizionGateway" \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.0' \
          -configuration Debug \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO

    - name: Test
      run: |
        xcodebuild test \
          -scheme "VizionGateway" \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.0' \
          -configuration Debug \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO

  deploy:
    name: Deploy
    needs: build
    runs-on: macos-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Provisioning
        env:
          PROVISIONING_PROFILE_BASE64: ${{ secrets.PROVISIONING_PROFILE_BASE64 }}
          CERTIFICATE_BASE64: ${{ secrets.CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
        run: |
          # Create keychain
          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security set-keychain-settings -t 3600 -l ~/Library/Keychains/build.keychain
          
          # Import certificate
          echo $CERTIFICATE_BASE64 | base64 --decode > certificate.p12
          security import certificate.p12 -k build.keychain -P $P12_PASSWORD -T /usr/bin/codesign
          
          # Import provisioning profile
          echo $PROVISIONING_PROFILE_BASE64 | base64 --decode > profile.mobileprovision
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
          
      - name: Build for Release
        run: |
          xcodebuild clean archive \
            -scheme "Vizion Gateway" \
            -configuration Release \
            -archivePath "Vizion Gateway.xcarchive" \
            CODE_SIGN_STYLE=Manual \
            PROVISIONING_PROFILE="$PROVISIONING_PROFILE_UUID" \
            CODE_SIGN_IDENTITY="$SIGNING_CERTIFICATE"
            
      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
            -archivePath "Vizion Gateway.xcarchive" \
            -exportOptionsPlist exportOptions.plist \
            -exportPath ./build
            
      - name: Upload to App Store
        env:
          APP_STORE_CONNECT_USERNAME: ${{ secrets.APP_STORE_CONNECT_USERNAME }}
          APP_STORE_CONNECT_PASSWORD: ${{ secrets.APP_STORE_CONNECT_PASSWORD }}
        run: |
          xcrun altool --upload-app -f "./build/Vizion Gateway.ipa" \
            -u "$APP_STORE_CONNECT_USERNAME" \
            -p "$APP_STORE_CONNECT_PASSWORD" \
            --type ios
            
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false 